DROP TABLE Countries CASCADE CONSTRAINTS;
DROP TABLE Athletes CASCADE CONSTRAINTS;
DROP TABLE Olympic_Games CASCADE CONSTRAINTS;
DROP TABLE Events CASCADE CONSTRAINTS;
DROP TABLE Olympic_Results CASCADE CONSTRAINTS;
DROP TABLE Medal_Tally CASCADE CONSTRAINTS;
DROP TABLE Athlete_Results CASCADE CONSTRAINTS;